### Support Vector Classifier with GridSearchCV

In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv('Advertising_data.csv',delimiter =',')

In [3]:
ds.head(5)

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
X=ds.loc[:,['Age','EstimatedSalary']]

In [5]:
y=ds.loc[:,['Purchased']]

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=254)

### Standard Scaler

In [7]:
ss=StandardScaler()

In [8]:
X_train=ss.fit_transform(X_train)

In [9]:
X_test=ss.fit_transform(X_test)

### Support Vector Classifier

In [10]:
svc=SVC(kernel='linear',random_state=0)
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [11]:
p_pred=svc.predict(X_test)

In [12]:
p_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

### Confusion Matrix

In [13]:
cm=confusion_matrix(y_test,p_pred)

In [14]:
cm

array([[59,  7],
       [11, 23]], dtype=int64)

### Accuracy Score


In [15]:
ac=accuracy_score(y_test,p_pred)
print('Accuracy Score :', ac,'%')

Accuracy Score : 0.82 %


### Use of Grid Search CV

In [16]:
parameter_list=[{'C':[0.1,0.5,1,510,50,100,100],'kernel':['linear']},
                {'C':[0.1,0.5,1,5,10,50,100,100],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]},
                {'degree':[1,2,3,4,5,6,7,8,9]},
                {'cache_size':[100,200,300,400,500]}
               ]

In [17]:
gscv=GridSearchCV(estimator=svc,
                  param_grid=parameter_list,
                  scoring='accuracy',
                  cv=10,
                  n_jobs=-1)

In [18]:
best_params=gscv.fit(X_train,y_train)

In [19]:
best_params.best_params_

{'C': 10, 'gamma': 0.5, 'kernel': 'rbf'}

In [20]:
best_params.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
best_params.best_score_

0.9433333333333334

### Support Vector Machine Using GridSearchCV Parameters

In [22]:
svc_gs=SVC(kernel='rbf',random_state=0,C=10,gamma=0.5)
svc_gs.fit(X_train,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
p_pred_gs=svc_gs.predict(X_test)

In [24]:
p_pred_gs

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

### Accuracy After GridSearchCV

In [25]:
ac=accuracy_score(y_test,p_pred_gs)
print('Accuracy Score :', ac,'%')

Accuracy Score : 0.85 %
